Ans 1: In the given code, the variable list_ is a Python list containing string elements, while the variable array_list is a NumPy array created from the list_. So, there is a difference in the data types of both variables.

In [1]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print("Data type of 'list_':", type(list_))
print("Data type of 'array_list':", type(array_list))


Data type of 'list_': <class 'list'>
Data type of 'array_list': <class 'numpy.ndarray'>


Ans 2:

In [2]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print data type of each element in 'list_'
print("Data type of elements in 'list_':")
for element in list_:
    print(type(element))

# Print data type of each element in 'array_list'
print("\nData type of elements in 'array_list':")
for element in array_list:
    print(type(element))


Data type of elements in 'list_':
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data type of elements in 'array_list':
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


Ans 3: Yes, there will be a difference in the data types of the elements present in both variables list_ and array_list.

In the original code, the array_list variable is created without specifying the data type, so by default, NumPy infers the data type of the elements based on the input data, which in this case are strings. Therefore, the data type of elements in array_list is numpy.str_.

However, when you change the array_list variable declaration to explicitly specify the data type as int, NumPy will try to convert the elements from strings to integers.

In [3]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

# Print data type of each element in 'list_'
print("Data type of elements in 'list_':")
for element in list_:
    print(type(element))

# Print data type of each element in 'array_list'
print("\nData type of elements in 'array_list':")
for element in array_list:
    print(type(element))


Data type of elements in 'list_':
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data type of elements in 'array_list':
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


Ans 4: 

In [4]:
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# (i) Find the shape of num_array
shape = num_array.shape

# (ii) Find the size of num_array
size = num_array.size

print("Shape of num_array:", shape)
print("Size of num_array:", size)


Shape of num_array: (2, 3)
Size of num_array: 6


Ans5: 

In [6]:
import numpy as np

# Create a 3x3 matrix of zeros
zeros_array = np.zeros((3, 3))

print(zeros_array)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Ans 6:

In [7]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

print(identity_matrix)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
